# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run
      run: java -jar target/a-puzzle-a-day.jar
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        # Optional. Commit message for the created commit.
        # Defaults to "Apply automatic changes"
        commit_message: Automated Change

        # Optional. Local and remote branch name where commit is going to be pushed
        #  to. Defaults to the current branch.
        #  You might need to set `create_branch: true` if the branch does not exist.
        branch: daily-resolve

        # Optional. Options used by `git-commit`.
        # See https://git-scm.com/docs/git-commit#_options
        commit_options: '--no-verify --signoff'

        # Optional glob pattern of files which should be added to the commit
        # Defaults to all (.)
        # See the `pathspec`-documentation for git
        # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
        # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
        file_pattern: test.png

        # Optional. Local file path to the repository.
        # Defaults to the root of the repository.
        repository: .

        # Optional commit user and author settings
#        commit_user_name: My GitHub Actions Bot # defaults to "github-actions[bot]"
#        commit_user_email: my-github-actions-bot@example.org # defaults to "github-actions[bot]@users.noreply.github.com"
#        commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run

        # Optional. Tag name being created in the local repository and
        # pushed to remote repository and defined branch.
#        tagging_message: 'v1.0.0'

        # Optional. Option used by `git-status` to determine if the repository is
        # dirty. See https://git-scm.com/docs/git-status#_options
        status_options: '--untracked-files=no'

        # Optional. Options used by `git-add`.
        # See https://git-scm.com/docs/git-add#_options
        add_options: '-u'

        # Optional. Options used by `git-push`.
        # See https://git-scm.com/docs/git-push#_options
        push_options: '--force'

        # Optional. Disable dirty check and always try to create a commit and push
        skip_dirty_check: true

        # Optional. Skip internal call to `git fetch`
        skip_fetch: true

        # Optional. Skip internal call to `git checkout`
        skip_checkout: true

        # Optional. Prevents the shell from expanding filenames.
        # Details: https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html
        disable_globbing: true

        # Optional. Create given branch name in local and remote repository.
        create_branch: true
